### ISSUE TITLE
Rewrite in TypeScript

### ISSUE THREAD

**Issue by jojonium** [bandaloo/afterlight-caves#59]
I know it'll be a pain, but JavaScript is starting to be cumbersome to work with. TypeScript is way more sustainable and less error-prone, plus it will give us access to a bunch of neat features and tools.

**Comment by bandaloo** [comment]
This is a big mood. I think after PAX, we should undertake this.

**Comment by bandaloo** [comment]
> This is a big mood. I think after PAX, we should undertake this.

My opinion on this has changed.... While it's tempting since I do like TypeScript, we've already done a good job putting all of our type information in jsdoc which gets interpreted by Visual Studio Code's TypeScript server anyways. There's just a lot of stuff to rewrite, and I'd rather focus on improving the game.

**Comment by jojonium** [comment]
I'm fine with closing this for now

**Comment by bandaloo** [comment]
Won't be undertaking this in the foreseeable future
